option(TASTY_CCACHE "Launch compiles through ccache when it is installed" ON)
if(TASTY_CCACHE)
  find_program(TASTY_CCACHE_PROGRAM ccache NO_CMAKE_FIND_ROOT_PATH)
  mark_as_advanced(TASTY_CCACHE_PROGRAM)
  if(TASTY_CCACHE_PROGRAM)
    foreach(lang C CXX)
      if(NOT CMAKE_${lang}_COMPILER_LAUNCHER)
        set(CMAKE_${lang}_COMPILER_LAUNCHER "${TASTY_CCACHE_PROGRAM}")
      endif()
    endforeach()
  endif()
endif()
