include_guard(GLOBAL)

find_path(TASTY_LIBCHDR_INCLUDE_DIR NAMES libchdr/chd.h)
find_library(TASTY_LIBCHDR_LIBRARY NAMES chdr)
mark_as_advanced(TASTY_LIBCHDR_INCLUDE_DIR TASTY_LIBCHDR_LIBRARY)

if(TASTY_LIBCHDR_INCLUDE_DIR AND TASTY_LIBCHDR_LIBRARY)
  set(TASTY_LIBCHDR_DETECTED ON)
else()
  set(TASTY_LIBCHDR_DETECTED OFF)
endif()

find_path(TASTY_MINIZIP_INCLUDE_DIR NAMES minizip/unzip.h)
find_library(TASTY_MINIZIP_LIBRARY NAMES minizip)
mark_as_advanced(TASTY_MINIZIP_INCLUDE_DIR TASTY_MINIZIP_LIBRARY)

if(TASTY_MINIZIP_INCLUDE_DIR AND TASTY_MINIZIP_LIBRARY)
  set(TASTY_MINIZIP_DETECTED ON)
else()
  set(TASTY_MINIZIP_DETECTED OFF)
endif()

message(STATUS "tasty decoders probed: libchdr=${TASTY_LIBCHDR_DETECTED} "
               "(${TASTY_LIBCHDR_LIBRARY}) minizip=${TASTY_MINIZIP_DETECTED} "
               "(${TASTY_MINIZIP_LIBRARY})")
