function(_gf_collect_tests dir out)
  get_property(_tests DIRECTORY "${dir}" PROPERTY TESTS)
  set(_all)
  foreach(_t IN LISTS _tests)
    list(APPEND _all "${dir}|${_t}")
  endforeach()
  get_property(_subs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
  foreach(_s IN LISTS _subs)
    _gf_collect_tests("${_s}" _sub)
    list(APPEND _all ${_sub})
  endforeach()
  set(${out} "${_all}" PARENT_SCOPE)
endfunction()

set(_gf_san_env)
if(CMAKE_CXX_FLAGS MATCHES "-fsanitize=[^ ]*address")
  set(_gf_san_env
      "ASAN_OPTIONS=detect_leaks=1:halt_on_error=1:abort_on_error=1:detect_stack_use_after_return=1"
      "UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1")
endif()

if(CMAKE_VERSION VERSION_LESS 3.28)
  if(_gf_san_env)
    message(FATAL_ERROR "tasty: a sanitizer build needs CMake 3.28 to set its runtime options")
  endif()
  message(STATUS "tasty: per-test TMPDIR needs CMake 3.28 (set_property TEST DIRECTORY); off")
  return()
endif()

_gf_collect_tests("${CMAKE_SOURCE_DIR}" _gf_tests)
if(NOT _gf_tests)
  return()
endif()
string(SHA1 _gf_tree_id "${CMAKE_BINARY_DIR}")
string(SUBSTRING "${_gf_tree_id}" 0 8 _gf_tree_id)
set(TASTY_TEST_TMP_ROOT "/tmp/gf-ctest-${_gf_tree_id}")
set(_gf_setup "file(REMOVE_RECURSE \"${TASTY_TEST_TMP_ROOT}\")\n")
foreach(_row IN LISTS _gf_tests)
  string(REPLACE "|" ";" _row "${_row}")
  list(GET _row 0 _dir)
  list(GET _row 1 _t)
  string(REGEX REPLACE "^tasty\\." "" _leaf "${_t}")
  string(APPEND _gf_setup "file(MAKE_DIRECTORY \"${TASTY_TEST_TMP_ROOT}/${_leaf}\")\n")
  set_property(TEST "${_t}" DIRECTORY "${_dir}" APPEND PROPERTY
               ENVIRONMENT "TMPDIR=${TASTY_TEST_TMP_ROOT}/${_leaf}" ${_gf_san_env})
  set_property(TEST "${_t}" DIRECTORY "${_dir}" APPEND PROPERTY FIXTURES_REQUIRED tasty_test_tmp)
endforeach()
file(WRITE "${CMAKE_BINARY_DIR}/test_tmp_setup.cmake" "${_gf_setup}")
add_test(NAME tasty.test_tmp_setup
         COMMAND "${CMAKE_COMMAND}" -P "${CMAKE_BINARY_DIR}/test_tmp_setup.cmake")
set_tests_properties(tasty.test_tmp_setup PROPERTIES FIXTURES_SETUP tasty_test_tmp)
