function(tasty_unit_test target)
  cmake_parse_arguments(PARSE_ARGV 1 A "EXCLUDE_FROM_ALL"
    "NAME;TIMEOUT;WORKING_DIRECTORY" "SOURCES;LIBS;INCLUDES;DEFINES;LABELS;COMMAND;PROPERTIES")
  if(NOT A_NAME OR NOT A_SOURCES)
    message(FATAL_ERROR "tasty_unit_test(${target}): NAME and SOURCES are required")
  endif()
  if(A_EXCLUDE_FROM_ALL)
    add_executable(${target} EXCLUDE_FROM_ALL ${A_SOURCES})
  else()
    add_executable(${target} ${A_SOURCES})
  endif()
  if(A_INCLUDES)
    target_include_directories(${target} PRIVATE ${A_INCLUDES})
  endif()
  if(A_DEFINES)
    target_compile_definitions(${target} PRIVATE ${A_DEFINES})
  endif()
  if(A_LIBS)
    target_link_libraries(${target} PRIVATE ${A_LIBS})
  endif()
  if(NOT A_COMMAND)
    set(A_COMMAND ${target})
  endif()
  add_test(NAME ${A_NAME} COMMAND ${A_COMMAND})
  set(_props ${A_PROPERTIES})
  if(A_TIMEOUT)
    list(APPEND _props TIMEOUT ${A_TIMEOUT})
  endif()
  if(A_LABELS)
    list(APPEND _props LABELS ${A_LABELS})
  endif()
  if(A_WORKING_DIRECTORY)
    list(APPEND _props WORKING_DIRECTORY ${A_WORKING_DIRECTORY})
  endif()
  if(_props)
    set_tests_properties(${A_NAME} PROPERTIES ${_props})
  endif()
endfunction()
